# Generated by Django 5.2.15 on 2026-07-08 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='action_icons/')),
                ('category', models.CharField(choices=[('RECYCLING', 'Recycling'), ('TREE_PLANTING', 'Tree Planting'), ('WATER_SAVING', 'Water Saving'), ('ENERGY_SAVING', 'Energy Saving'), ('WASTE_REDUCTION', 'Waste Reduction'), ('SUSTAINABLE_TRANSPORT', 'Sustainable Transport'), ('COMMUNITY_SERVICE', 'Community Service'), ('SUSTAINABLE_DIET', 'Sustainable Diet'), ('OTHER', 'Other')], max_length=30)),
                ('default_points', models.PositiveIntegerField()),
                ('co2_impact_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('how_to_play', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='challenge_images/')),
                ('challenge_type', models.CharField(choices=[('RECYCLING', 'Recycling'), ('TREE_PLANTING', 'Tree Planting'), ('WATER_SAVING', 'Water Saving'), ('ENERGY_SAVING', 'Energy Saving'), ('WASTE_REDUCTION', 'Waste Reduction'), ('SUSTAINABLE_TRANSPORT', 'Sustainable Transport'), ('COMMUNITY_SERVICE', 'Community Service'), ('SUSTAINABLE_DIET', 'Sustainable Diet'), ('OTHER', 'Other')], max_length=30)),
                ('challenge_format', models.CharField(choices=[('GOAL', 'Goal Achieve'), ('TIMELINE', 'Timeline')], default='TIMELINE', max_length=10)),
                ('goal_metric', models.CharField(blank=True, choices=[('TOTAL_ACTIONS', 'Total Actions Logged'), ('TOTAL_POINTS', 'Total Points Earned')], max_length=20, null=True)),
                ('goal_title', models.CharField(blank=True, max_length=255)),
                ('goal_count', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('prize_type', models.CharField(blank=True, choices=[('VOUCHER', 'Voucher'), ('BADGE', 'Badge'), ('PHYSICAL_ITEM', 'Physical Item'), ('BONUS_POINTS', 'Bonus Points')], max_length=20)),
                ('actions', models.ManyToManyField(blank=True, related_name='challenges', to='challenges.actioncatalogitem')),
                ('communities', models.ManyToManyField(blank=True, related_name='challenges', to='accounts.community')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('JOINED', 'Joined'), ('LEFT', 'Left')], default='JOINED', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_awarded', models.PositiveIntegerField(help_text='Snapshot of the catalog item points at submission time.')),
                ('proof_image', models.ImageField(upload_to='action_proofs/')),
                ('caption', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('action_catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='challenges.actioncatalogitem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_action_logs', to=settings.AUTH_USER_MODEL)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.challengeparticipation')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengePrize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField(help_text='1 = first prize, 2 = second prize, etc.')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prize_images/')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='challenges.challenge')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('challenge', 'rank')},
            },
        ),
    ]
