# Generated by Django 5.2.15 on 2026-07-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='co2_impact_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of the catalog item CO2 impact at submission time.', max_digits=8),
        ),
    ]
