# Generated by Django 5.2.15 on 2026-07-12 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_first_name_remove_user_last_name_and_more'),
        ('challenges', '0002_actionlog_co2_impact_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyActionSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('action_catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='challenges.actioncatalogitem')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_settings', to='accounts.company')),
            ],
            options={
                'unique_together': {('company', 'action_catalog_item')},
            },
        ),
    ]
