# Generated by Django 5.2.15 on 2026-07-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_companyactionsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncatalogitem',
            name='waste_recycled_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='actioncatalogitem',
            name='water_saved_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='waste_recycled_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of the catalog item waste-recycled impact at submission time.', max_digits=8),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='water_saved_liters',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of the catalog item water-saved impact at submission time.', max_digits=8),
        ),
    ]
